#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bootstrap_script="$project_root/bin/bootstrap-github-oidc"
backend_root="$project_root/backend"
ami_workflow="$project_root/.github/workflows/build-backend-ami.yml"

assert_contains() {
  local pattern="$1"
  local file="$2"
  grep -Fq -- "$pattern" "$file" || {
    echo "missing contract: $pattern ($file)" >&2
    exit 1
  }
}

assert_absent() {
  local pattern="$1"
  local file="$2"
  if grep -Fq -- "$pattern" "$file"; then
    echo "forbidden contract found: $pattern ($file)" >&2
    exit 1
  fi
}

assert_absent '"Action": "ec2:*"' "$bootstrap_script"
assert_contains '"ec2:RunInstances"' "$bootstrap_script"
assert_contains '"ec2:TerminateInstances"' "$bootstrap_script"
assert_contains '"ec2:CreateKeyPair"' "$bootstrap_script"
assert_contains '"ec2:DeleteKeyPair"' "$bootstrap_script"
assert_contains '"ec2:StopInstances"' "$bootstrap_script"
assert_contains '"ec2:DescribeAddressesAttribute"' "$bootstrap_script"
assert_contains '"ec2:DescribeInstanceTypes"' "$bootstrap_script"
assert_contains '"ec2:DescribePrefixLists"' "$bootstrap_script"
assert_contains '"ec2:CreateRouteTable", "ec2:CreateSecurityGroup", "ec2:CreateSubnet"' "$bootstrap_script"
assert_contains '"ec2:CreateVpcEndpoint", "ec2:RunInstances"' "$bootstrap_script"
assert_contains '"iam:AttachRolePolicy"' "$bootstrap_script"
assert_contains '"iam:DetachRolePolicy"' "$bootstrap_script"
assert_contains '"ec2:ModifyImageAttribute"' "$bootstrap_script"
assert_contains '"ec2:DeregisterImage"' "$bootstrap_script"
assert_contains '"ec2:ResourceTag/Application": "${application_name}"' "$bootstrap_script"
assert_contains '"aws:RequestTag/Application": "${application_name}"' "$bootstrap_script"
assert_contains '"Sid": "PassEnvironmentBackendRole"' "$bootstrap_script"
assert_contains '"Action": "iam:PassRole"' "$bootstrap_script"
assert_contains '"Resource": "${backend_role_arn}"' "$bootstrap_script"
assert_contains '--route53-zone-id is required unless --create-hosted-zone is used' "$bootstrap_script"
assert_contains 'route53_resource="arn:aws:route53:::hostedzone/${route53_zone_id}"' "$bootstrap_script"
assert_contains 'resource "terraform_data" "production_destroy_guard"' "$backend_root/main.tf"
assert_contains 'prevent_destroy = var.environment == "production"' "$backend_root/main.tf"
assert_contains 'resource "terraform_data" "production_destroy_guard"' "$backend_root/modules/compute/main.tf"
assert_contains 'resource "terraform_data" "production_destroy_guard"' "$backend_root/modules/networking/main.tf"
assert_contains 'resource "terraform_data" "production_destroy_guard"' "$backend_root/modules/deployment-artifacts/main.tf"
assert_contains 'resource "terraform_data" "production_destroy_guard"' "$backend_root/modules/dns-tls/main.tf"
assert_contains 'expiration {' "$backend_root/modules/deployment-artifacts/main.tf"
assert_contains 'default     = 30' "$backend_root/modules/deployment-artifacts/variables.tf"
assert_contains 'docs/mkdocs/recovery.md' "$project_root/backend/README.md"
assert_contains 'Recovery point objective (RPO): 24 hours.' "$project_root/docs/mkdocs/recovery.md"
assert_contains 'Recovery time objective (RTO): 4 hours.' "$project_root/docs/mkdocs/recovery.md"
assert_contains 'Restore rehearsal: quarterly for production.' "$project_root/docs/mkdocs/recovery.md"
assert_contains 'Docker named-volume state, including Caddy certificate state' "$project_root/docs/mkdocs/recovery.md"
assert_contains 'resource "aws_backup_plan" "data"' "$backend_root/main.tf"
assert_contains 'rule_name         = "daily"' "$backend_root/main.tf"
assert_contains 'delete_after = 7' "$backend_root/main.tf"
assert_contains 'rule_name         = "weekly"' "$backend_root/main.tf"
assert_contains 'delete_after = 28' "$backend_root/main.tf"
assert_contains 'resources = [module.compute.data_volume_arn]' "$backend_root/main.tf"
assert_contains 'Production must keep data-volume backups enabled.' "$backend_root/variables.tf"
assert_contains 'printf '\''SecureString'\''' "$project_root/bin/bootstrap-backend-parameters"
assert_contains '--non-secret' "$project_root/bin/bootstrap-backend-parameters"
assert_contains 'backend/modules/compute' "$project_root/bin/quality"
assert_contains 'docs/mkdocs/quality.md' "$project_root/README.md"
assert_contains 'docs/mkdocs/change-management.md' "$project_root/README.md"
assert_contains 'bash bin/docs lint' "$project_root/bin/quality"
assert_contains 'Reuse a matching live AMI when available' "$ami_workflow"
assert_contains 'poorman-aws-${APPLICATION_NAME}-ami' "$ami_workflow"
assert_contains 'AMI_BUILD_FINGERPRINT' "$ami_workflow"
assert_contains 'ssm get-parameter' "$ami_workflow"
assert_contains 'ssm put-parameter' "$ami_workflow"
assert_absent 'environment_admin_token' "$ami_workflow"
assert_contains 'ssm get-parameter' "$project_root/bin/resolve-ami-id"
assert_contains 'ssm:PutParameter' "$bootstrap_script"
assert_contains 'ssm:GetParameter' "$bootstrap_script"
assert_contains 'route53:ListHostedZones' "$bootstrap_script"
assert_contains 'bucket_prefix = var.bucket_name == null ? local.bucket_prefix : null' "$project_root/backend/modules/deployment-artifacts/main.tf"
assert_contains 'substr(var.name, 0, 17)' "$project_root/backend/modules/deployment-artifacts/main.tf"
assert_contains 'substr(sha1(var.name), 0, 8)' "$project_root/backend/modules/deployment-artifacts/main.tf"
assert_contains 'trimspace(var.route53_zone_id) == "" ? null' "$project_root/backend/modules/dns-tls/main.tf"
assert_contains 'secrets: inherit' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'secrets.aws_role_arn || secrets.AWS_ROLE_ARN' "$ami_workflow"
assert_contains 'aws ec2 describe-images' "$ami_workflow"
assert_contains 'retry_delays=(2 5 10 15)' "$ami_workflow"
assert_contains '--retry-all-errors' "$ami_workflow"
assert_contains 'is still pending; retrying validation.' "$ami_workflow"
assert_contains 'if: needs.guard.outputs.reuse != '\''true'\''' "$ami_workflow"
assert_contains 'needs: [guard, build]' "$ami_workflow"
assert_contains 'value: ${{ jobs.publish.outputs.ami_id }}' "$ami_workflow"
assert_contains 'uses: hashicorp/setup-packer@v3' "$ami_workflow"
assert_contains 'resolve-public-egress-cidr' "$project_root/bin/build-backend-ami"
assert_contains 'bash bin/build-backend-ami' "$ami_workflow"
assert_contains 'bash bin/cleanup-packer-resources' "$ami_workflow"
assert_contains 'ec2 terminate-instances' "$project_root/bin/cleanup-packer-resources"
assert_contains 'ec2 delete-key-pair' "$project_root/bin/cleanup-packer-resources"
assert_contains 'if: always() && needs.guard.result == '\''success'\''' "$ami_workflow"
assert_contains 'PoormanAwsBuildRun' "$project_root/backend/packer/application-backend.pkr.hcl"
assert_contains 'packer build -on-error=cleanup' "$project_root/bin/build-backend-ami"
assert_contains "packer validate \\" "$project_root/bin/build-backend-ami"
assert_contains "packer build -on-error=cleanup -machine-readable -color=false \\" "$project_root/bin/build-backend-ami"
assert_absent "printf 'ssh_cidr=%s\\n'" "$ami_workflow"
assert_absent 'steps.network.outputs.ssh_cidr' "$ami_workflow"
assert_contains 'build_fingerprint' "$project_root/backend/packer/application-backend.pkr.hcl"
assert_contains 'build_or_resolve_ami:' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'uses: kanutocd/poorman-aws/.github/workflows/build-backend-ami.yml@v0.1.0' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_absent 'environment_admin_token' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'secrets: inherit' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'needs.build_or_resolve_ami.outputs.ami_id' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'Repair tainted retained EIP state' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'tofu state pull' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'select(.status? == "tainted")' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'tofu untaint module.compute.aws_eip.this' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_contains 'Refusing to untaint EIP: live allocation or ownership tags do not match.' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_absent 'Resolve AMI ID from artifact or environment variable' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_absent 'ami_ssh_cidr' "$project_root/.github/workflows/deploy-backend-infra.yml"
assert_absent '__AMI_SSH_CIDR__' "$project_root/bin/poorman-aws"
assert_absent 'build-backend-ami.yml' "$project_root/.github/workflows/kill-non-production.yml"

echo "Policy contract checks passed"
